@Etkezes_API_HostAddress = http://192.168.10.66:5000

GET {{Etkezes_API_HostAddress}}/
Accept: application/json

###
GET {{Etkezes_API_HostAddress}}/sync/dates

###
POST {{Etkezes_API_HostAddress}}/sync/loginusers
Content-Type: application/json

 [{
    "name":"admin",
    "fpid":"10001",
    "userName":"admin",
    "password":""
 }]


 ###
@osztaly=5.b
GET {{Etkezes_API_HostAddress}}/users/{{osztaly}}

###
GET {{Etkezes_API_HostAddress}}/users
###
POST {{Etkezes_API_HostAddress}}/etkezes
content-type: application/json
{
    "datum":"2024-06-10",
    "userId":10001,
    "menu":"A",
    "adag":"nagy adag",
    "darab":1,
    "elfogyasztva":false,
    "user":{
        "name":"admin",
        "osztaly":"5.b"
    }
}
###
GET {{Etkezes_API_HostAddress}}/maietkezesek
###
POST {{Etkezes_API_HostAddress}}/users
content-type: application/json
[
    {"Id":72836081976,
    "Name":"Abai Nóra",
    "FpId":0,
    "FingerPrint1":"",
    "FingerPrint2":"",
    "Osztaly":"10.b",
    "Etkezik":false,
    "Created":"2026-03-29T20:01:17.6724824Z",
    "Uploaded":"2026-03-29T20:01:17.6724824Z",
    "Updated":"2026-03-29T20:01:17.6724824Z"},
    {"Id":73332329014,
    "Name":"Ádám Barnabás Mihály",
    "FpId":0,
    "FingerPrint1":"",
    "FingerPrint2":"",
    "Osztaly":"9.b",
    "Etkezik":false,
    "Created":"2026-03-29T20:01:17.6724901Z",
    "Uploaded":"2026-03-29T20:01:17.6724901Z",
    "Updated":"2026-03-29T20:01:17.6724901Z"}
  ]
  ###
  GET {{Etkezes_API_HostAddress}}/etkezesek/78965412311